### ISSUE TITLE
Unkown Pk91 Version (CLOSED)

### ISSUE THREAD

**Issue by denzelxrt** [jimzrt/Incognito_RCM#38]
iam getting a "Unkown Pk91 Version" and i dont know what to do help me pls

**Comment by Masamune3210** [comment]
1. Pkg1, not pk91
2. Update Lockpick_RCM and atmos to latest

**Comment by Amazon-Inc** [comment]
I did and it

Sent from Yahoo Mail on Android
<https://go.onelink.me/107872968?pid=InProduct&c=Global_Internal_YGrowth_AndroidEmailSig__AndroidUsers&af_wl=ym&af_sub1=Internal&af_sub2=Global_YGrowth&af_sub3=EmailSignature>

On Sun, 3 Jan 2021 at 7:06 pm, Masamune3210
<notifications@github.com> wrote:


   1. Pkg1, not pk91
   2. Update Lockpick_RCM and atmos to latest

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jimzrt/Incognito_RCM/issues/38#issuecomment-753662580>,
or unsubscribe

**Comment by Amazon-Inc** [comment]
I did and it does say pk91

Sent from Yahoo Mail on Android 
 
  On Sun, 3 Jan 2021 at 7:06 pm, Masamune3210<notifications@github.com> wrote:   

   
   - Pkg1, not pk91
   - Update Lockpick_RCM and atmos to latest

**Comment by Masamune3210** [comment]
Take a picture?

**Comment by Amazon-Inc** [comment]
Sorry it did say pkg1 it look like a 9 to me
